// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package pack0

import (
	"github.com/NeoGitCrt1/wiredemo/model"
	"github.com/google/wire"
)

// Injectors from wire_p0.go:

func InitEndingA(name string) model.EndingA {
	player := model.NewPlayer(name)
	monster := model.NewMonster()
	endingA := model.NewEndingA(player, monster)
	return endingA
}

func InitEndingB(name string) model.EndingB {
	player := model.NewPlayer(name)
	monster := model.NewMonster()
	endingB := model.NewEndingB(player, monster)
	return endingB
}

// wire_p0.go:

var monsterPlayerSet = wire.NewSet(model.NewMonster, model.NewPlayer)
